name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit
        run: pre-commit run --all-files

  build:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull Build Docker Image
        run: |
          docker pull ghcr.io/htoik/fourier-mellin/manylinux_x86_64:latest

      - name: Build & test inside Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w /workspace \
            ghcr.io/htoik/fourier-mellin/manylinux_x86_64:latest \
            bash -lc "\
              yum install -y gcc gcc-c++ && \
              \
              mkdir -p build/release && \
              cd build/release && \
              cmake -DCMAKE_BUILD_TYPE=Release ../.. && \
              make -j && \
              \
              python -m pip install --upgrade pip setuptools wheel && \
              pip install . && \
              \
              pip install pytest && \
              pytest -q \
            "

      # - name: Install build tools
      #   run: |
      #     yum install -y gcc gcc-c++

      # - name: Build C++
      #   working-directory: ${{ github.workspace }}
      #   run: |
      #     mkdir -p build/release
      #     cd build/release
      #     cmake -DCMAKE_BUILD_TYPE=Release ../..
      #     make -j

      # - name: Install Python binding
      #   run: |
      #     python -m pip install --upgrade pip setuptools wheel
      #     pip install .

      # - name: Run Python tests
      #   run: |
      #     pip install pytest
      #     pytest -q
